#!/bin/bash -x

isFullTime=1
isParttime=2
randomcheck=$((RANDOM%3))
empRatePerHr=20

if [ $isPartime -eq $randomcheck ]
then
        empHrs=4
elif [ $isFullTime -eq $randomcheck ]
then
       empHrs=8
else
       empHrs=0
fi

salary=$(($empHrs*$empRatePerHr))
